/*
    AUTHOR:       Taha Yasir Kiroglu
    DATE:         10.07.2018
    DESCRIPTION   package definition of web_calculator
    FILE NAME     web_calculator.pks
    VERSION:      1.0.2
*/
CREATE OR REPLACE PACKAGE SYS.WEB_CALCULATOR
AS
	FUNCTION CALCULATOR(PIN_NUMBER1 NUMBER, PIN_NUMBER2 NUMBER, PIS_OPERATION VARCHAR2) RETURN VARCHAR2;	
END WEB_CALCULATOR;