CREATE OR REPLACE PACKAGE HR.ORNEK_CRUD_ISLEMLERI 
AS
    PROCEDURE INSERT_N_VALUES(pin_number_count NUMBER);
    PROCEDURE DELETE_FIRST_N_VALUES(pin_number_count NUMBER);
    PROCEDURE UPDATE_FIRST_N_VALUES(pin_number_count NUMBER);
END;
/

CREATE OR REPLACE PACKAGE BODY HR.ORNEK_CRUD_ISLEMLERI 
AS
    PROCEDURE INSERT_N_VALUES(pin_number_count NUMBER)
    IS
    BEGIN
        for n in 1..pin_number_count LOOP
            INSERT INTO stajyer(STAJYER_NO, STAJYER_ADI, STAJYER_SOYADI) VALUES (n, 'INSERTED', 'USER');
        END LOOP;
    END INSERT_N_VALUES;

    PROCEDURE DELETE_FIRST_N_VALUES(pin_number_count NUMBER)
    IS
    BEGIN
        FOR n IN 1..pin_number_count LOOP
            DELETE FROM STAJYER WHERE STAJYER_NO = n;
        END LOOP;
    END DELETE_FIRST_N_VALUES;

    PROCEDURE UPDATE_FIRST_N_VALUES(pin_number_count NUMBER)
    IS
    BEGIN
        FOR n IN 1..pin_number_count LOOP
            UPDATE STAJYER SET STAJYER_ADI = 'UPDATED', STAJYER_SOYADI = 'SURNAME' WHERE STAJYER_NO = n;
        END LOOP;
    END UPDATE_FIRST_N_VALUES;
END ORNEK_CRUD_ISLEMLERI;
/

CREATE OR REPLACE PACKAGE HR.BENCHMARK_UTILITIES
BEGIN

    -- hr.ORNEK_CRUD_ISLEMLERI.INSERT_N_VALUES(30);
    -- UPDATE_FIRST_N_VALUES(30);
    -- hr.ORNEK_CRUD_ISLEMLERI.DELETE_FIRST_N_VALUES(30);
    -- SELECT * FROM hr.STAJYER;
    -- DELETE FROM STAJYER WHERE STAJYER_NO > 0;
END;